CREATE TABLE IF NOT EXISTS public.authors(
        id_author bigint generated by default as identity NOT NULL,
        name_author VARCHAR(255) not null,
        year_author VARCHAR(255),
        unique (name_author),
        primary key (id_author)

    );

CREATE TABLE IF NOT EXISTS public.books(
            id_book bigint generated by default as identity NOT NULL,
            name_book VARCHAR(255),
            year_book VARCHAR(255),
            id_author bigint,
            foreign key (id_author) references authors(id_author)

            ON UPDATE CASCADE,
            UNIQUE (name_book, id_author),
            primary key (id_book)
    );
CREATE TABLE IF NOT EXISTS public.genres(
        id_genre bigint generated by default as identity NOT NULL,
        name_genre VARCHAR(255) not null,
        unique (name_genre),
        primary key (id_genre)
    );


CREATE TABLE IF NOT EXISTS public.comments(
        id_comment bigint generated by default as identity NOT NULL,
        text VARCHAR(255) not null,
        id_book bigint,
        primary key (id_comment),
        foreign key (id_book) references books(id_book)
            ON UPDATE CASCADE
    );
CREATE TABLE IF NOT EXISTS public.book_genre(
        id_book bigint not null,
        id_genre bigint not null,

        foreign key (id_genre) references genres(id_genre)
            ON UPDATE CASCADE,

        foreign key (id_book) references books(id_book)
            ON UPDATE CASCADE

    );
